
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 16;
  public static final int EQUAL = 10;
  public static final int PREFIX = 8;
  public static final int EOF = 0;
  public static final int CONCAT = 2;
  public static final int LBRAC = 5;
  public static final int IF = 12;
  public static final int FUNCPARBRAC = 15;
  public static final int ELSE = 13;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int RPAREN = 4;
  public static final int IDENTIFIER = 14;
  public static final int SUFFIX = 9;
  public static final int LPAREN = 3;
  public static final int RBRAC = 6;
  public static final int REVERSE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONCAT",
  "LPAREN",
  "RPAREN",
  "LBRAC",
  "RBRAC",
  "COMMA",
  "PREFIX",
  "SUFFIX",
  "EQUAL",
  "REVERSE",
  "IF",
  "ELSE",
  "IDENTIFIER",
  "FUNCPARBRAC",
  "STRING_LITERAL"
  };
}

